//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sembarangKasir
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaksi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public transaksi()
        {
            this.uang_transaksi = new HashSet<uang_transaksi>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_barang { get; set; }
        public Nullable<System.DateTime> tanggal { get; set; }
        public Nullable<int> qty { get; set; }
    
        public virtual master_barang master_barang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<uang_transaksi> uang_transaksi { get; set; }
    }
}
