//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sembarangKasir
{
    using System;
    using System.Collections.Generic;
    
    public partial class uang_transaksi
    {
        public int id { get; set; }
        public Nullable<int> id_transaksi { get; set; }
        public Nullable<int> income { get; set; }
    
        public virtual transaksi transaksi { get; set; }
    }
}
